### ISSUE TITLE
BackupBuddy/Updates: Jenn needs instructions!

### ISSUE THREAD

**Issue by JShapland** [halfempty/coveredwithfur#19]
What's automatic and what do I need to remember to back up/update? How often and how?

**Comment by halfempty** [comment]
@JShapland 

**Regarding backups:** You don't have to do anything, they're automatic. The database backs-up each day, and a complete files + database is performed each week.

**Regarding plugins:** In the end, we're going to only have a few: 
- _Advanced Custom Fields_ is a paid plugin. I will keep the license paid (I have a universal license I use on many sites), so updates should continue to appear via the Dashboard;
- Ditto _Backupbuddy_;
- _Carolyn Google Analytics_ is a simple one I made myself;
- and there's _Ubergrid_.

It is probably okay to update these when ever they say they need updating. But you should read the notes before doing so, because sometimes they will say that it breaks compatibility. In those cases you should contact me.

**Regarding WordPress updates:** Again, it's probably okay to apply the updates as they're released. But you should read the notes before applying them. And I'm available if there's any problems.
